name: CI

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: macos-latest

    steps:
      - run: git clone --recurse-submodules https://github.com/Tracktion/tracktion_engine.git
      