name: CI

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          cd tracktion_engine-develop
          mkdir build
          cd build
          cmake ../tracktion_engine-develop -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64
          cmake --build . --config Release
      